apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demoproject
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/FrederiqueRetsema/kubernetes-test-repo.git
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'