version: '2'
run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - promlinter
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    copyloopvar:
      check-alias: true
    gocritic:
      disabled-checks:
        - assignOp
        - ifElseChain
  exclusions:
    rules:
      - linters:
          - lll
        path: api/.*
      - linters:
          - lll
        path: internal/.*
      - linters:
          - dupl
        path: .*_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
