# mockery configuration docs for the version used by this project
# https://vektra.github.io/mockery/v2.45/configuration/
with-expecter: true
packages:
  github.com/argoproj-labs/ephemeral-access/internal/accessrequest:
    config:
      dir: "internal/accessrequest/mocks"
      outpkg: "mocks"
    interfaces:
      K8sClient:
