interface Window {
  EPHEMERAL_ACCESS_VARS: {
    EPHEMERAL_ACCESS_DEFAULT_DISABLED: string;
    EPHEMERAL_ACCESS_LABEL_KEY: string;
    EPHEMERAL_ACCESS_LABEL_VALUE: string;
    EPHEMERAL_ACCESS_MAIN_BANNER: string;
    EPHEMERAL_ACCESS_MAIN_BANNER_ADDITIONAL_INFO_LINK: string;
    EPHEMERAL_ACCESS_CHANGE_REQUEST_URL: string;
    EPHEMERAL_ACCESS_DEFAULT_ROLE: string;
  };
}

