interface Window {
  GLOBAL_ARGOCD_ACCESS_EXT_LABEL_KEY: string;
  GLOBAL_ARGOCD_ACCESS_EXT_LABEL_VALUE: string;
  GLOBAL_ARGOCD_ACCESS_EXT_MAIN_BANNER: string;
  GLOBAL_ARGOCD_ACCESS_EXT_MAIN_BANNER_ADDITIONAL_INFO_LINK: string;
  GLOBAL_ARGOCD_ACCESS_EXT_CHANGE_REQUEST_URL: string;
}
