apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  labels:
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
data:
  {}
  ### Log configurations
  # backend.log.level: info
  # backend.log.format: json
  # controller.log.level: info
  # controller.log.format: json

  ### Backend configurations
  ## The API server port.
  # backend.port: '8888'
  ## The address the metric endpoint binds to.
  # backend.metrics.address: :8883
  ## If set the metrics endpoint is served securely.
  # backend.metrics.secure: 'true'

  # ### Controller configurations
  ## The controler server port.
  # controller.port: '8081'
  ## Enable leader election for controller manager.
  # controller.leader.election.enabled: 'true'
  ## The address the probe endpoint binds to.
  # controller.health.probe.address: :8082
  ## If set, HTTP/2 will be enabled for the metrics and webhook servers.
  # controller.http2.enabled: 'true'
  ## Determines the interval the controller will requeue an AccessRequest.
  # controller.requeue.interval: 1s
  ## The address the metric endpoint binds to.
  # controller.metrics.address: :8083
  ## If set the metrics endpoint is served securely.
  # controller.metrics.secure: 'true'
