---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ephemeral-access.argoproj-labs.io
  resources:
  - accessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ephemeral-access.argoproj-labs.io
  resources:
  - accessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - ephemeral-access.argoproj-labs.io
  resources:
  - accessrequests/status
  verbs:
  - get
  - patch
  - update
