apiVersion: ephemeral-access.argoproj-labs.io/v1alpha1
kind: AccessRequest
metadata:
  labels:
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
  name: some-application-username
  namespace: ephemeral
spec:
  duration: '1m'
  targetRoleName: ephemeral-write-access
  appProject: 
    name: some-argocd-appproject
    namespace: some-namespace
  subjects:
    - username: some_user@fakedomain.com
