# This is an example file provided to ilustrate how AccessRequest resources
# can be applied. It should not be applied to a local environment as it requires
# a valid Argo CD Application and AppProject to exist.
apiVersion: ephemeral-access.argoproj-labs.io/v1alpha1
kind: AccessRequest
metadata:
  name: some-application-username
  namespace: argocd
spec:
  duration: '1m'
  role:
    friendlyName: Write Access
    ordinal: 0
    templateRef:
      namespace: argocd-ephemeral-access
      name: write-template
  application:
    name: some-argocd-app
    namespace: the-app-ns
  subject:
    username: some_user@fakedomain.com
