apiVersion: ephemeral-access.argoproj-labs.io/v1alpha1
kind: AccessRequest
metadata:
  labels:
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
  name: some-application-username
  namespace: argocd-ephemeral-access
spec:
  duration: '1m'
  role:
    friendlyName: Write Access
    ordinal: 0
    templateRef:
      namespace: argocd-ephemeral-access
      name: write-template
  application:
    name: some-argocd-app
    namespace: the-app-ns
  subject:
    username: some_user@fakedomain.com
