// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/argoproj-labs/ephemeral-access/internal/backend"

	mock "github.com/stretchr/testify/mock"

	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	v1alpha1 "github.com/argoproj-labs/ephemeral-access/api/ephemeral-access/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateAccessRequest provides a mock function with given fields: ctx, key, binding
func (_m *MockService) CreateAccessRequest(ctx context.Context, key *backend.AccessRequestKey, binding *v1alpha1.AccessBinding) (*v1alpha1.AccessRequest, error) {
	ret := _m.Called(ctx, key, binding)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessRequest")
	}

	var r0 *v1alpha1.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, *v1alpha1.AccessBinding) (*v1alpha1.AccessRequest, error)); ok {
		return rf(ctx, key, binding)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, *v1alpha1.AccessBinding) *v1alpha1.AccessRequest); ok {
		r0 = rf(ctx, key, binding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.AccessRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.AccessRequestKey, *v1alpha1.AccessBinding) error); ok {
		r1 = rf(ctx, key, binding)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateAccessRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessRequest'
type MockService_CreateAccessRequest_Call struct {
	*mock.Call
}

// CreateAccessRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key *backend.AccessRequestKey
//   - binding *v1alpha1.AccessBinding
func (_e *MockService_Expecter) CreateAccessRequest(ctx interface{}, key interface{}, binding interface{}) *MockService_CreateAccessRequest_Call {
	return &MockService_CreateAccessRequest_Call{Call: _e.mock.On("CreateAccessRequest", ctx, key, binding)}
}

func (_c *MockService_CreateAccessRequest_Call) Run(run func(ctx context.Context, key *backend.AccessRequestKey, binding *v1alpha1.AccessBinding)) *MockService_CreateAccessRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.AccessRequestKey), args[2].(*v1alpha1.AccessBinding))
	})
	return _c
}

func (_c *MockService_CreateAccessRequest_Call) Return(_a0 *v1alpha1.AccessRequest, _a1 error) *MockService_CreateAccessRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateAccessRequest_Call) RunAndReturn(run func(context.Context, *backend.AccessRequestKey, *v1alpha1.AccessBinding) (*v1alpha1.AccessRequest, error)) *MockService_CreateAccessRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessRequest provides a mock function with given fields: ctx, key, roleName
func (_m *MockService) GetAccessRequest(ctx context.Context, key *backend.AccessRequestKey, roleName string) (*v1alpha1.AccessRequest, error) {
	ret := _m.Called(ctx, key, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessRequest")
	}

	var r0 *v1alpha1.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, string) (*v1alpha1.AccessRequest, error)); ok {
		return rf(ctx, key, roleName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, string) *v1alpha1.AccessRequest); ok {
		r0 = rf(ctx, key, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.AccessRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.AccessRequestKey, string) error); ok {
		r1 = rf(ctx, key, roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAccessRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessRequest'
type MockService_GetAccessRequest_Call struct {
	*mock.Call
}

// GetAccessRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key *backend.AccessRequestKey
//   - roleName string
func (_e *MockService_Expecter) GetAccessRequest(ctx interface{}, key interface{}, roleName interface{}) *MockService_GetAccessRequest_Call {
	return &MockService_GetAccessRequest_Call{Call: _e.mock.On("GetAccessRequest", ctx, key, roleName)}
}

func (_c *MockService_GetAccessRequest_Call) Run(run func(ctx context.Context, key *backend.AccessRequestKey, roleName string)) *MockService_GetAccessRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.AccessRequestKey), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetAccessRequest_Call) Return(_a0 *v1alpha1.AccessRequest, _a1 error) *MockService_GetAccessRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAccessRequest_Call) RunAndReturn(run func(context.Context, *backend.AccessRequestKey, string) (*v1alpha1.AccessRequest, error)) *MockService_GetAccessRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppProject provides a mock function with given fields: ctx, name, namespace
func (_m *MockService) GetAppProject(ctx context.Context, name string, namespace string) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetAppProject")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAppProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppProject'
type MockService_GetAppProject_Call struct {
	*mock.Call
}

// GetAppProject is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockService_Expecter) GetAppProject(ctx interface{}, name interface{}, namespace interface{}) *MockService_GetAppProject_Call {
	return &MockService_GetAppProject_Call{Call: _e.mock.On("GetAppProject", ctx, name, namespace)}
}

func (_c *MockService_GetAppProject_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockService_GetAppProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetAppProject_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockService_GetAppProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAppProject_Call) RunAndReturn(run func(context.Context, string, string) (*unstructured.Unstructured, error)) *MockService_GetAppProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplication provides a mock function with given fields: ctx, name, namespace
func (_m *MockService) GetApplication(ctx context.Context, name string, namespace string) (*unstructured.Unstructured, error) {
	ret := _m.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 *unstructured.Unstructured
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*unstructured.Unstructured, error)); ok {
		return rf(ctx, name, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *unstructured.Unstructured); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unstructured.Unstructured)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockService_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockService_Expecter) GetApplication(ctx interface{}, name interface{}, namespace interface{}) *MockService_GetApplication_Call {
	return &MockService_GetApplication_Call{Call: _e.mock.On("GetApplication", ctx, name, namespace)}
}

func (_c *MockService_GetApplication_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockService_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetApplication_Call) Return(_a0 *unstructured.Unstructured, _a1 error) *MockService_GetApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetApplication_Call) RunAndReturn(run func(context.Context, string, string) (*unstructured.Unstructured, error)) *MockService_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrantingAccessBinding provides a mock function with given fields: ctx, roleName, namespace, groups, app, project
func (_m *MockService) GetGrantingAccessBinding(ctx context.Context, roleName string, namespace string, groups []string, app *unstructured.Unstructured, project *unstructured.Unstructured) (*v1alpha1.AccessBinding, error) {
	ret := _m.Called(ctx, roleName, namespace, groups, app, project)

	if len(ret) == 0 {
		panic("no return value specified for GetGrantingAccessBinding")
	}

	var r0 *v1alpha1.AccessBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, *unstructured.Unstructured, *unstructured.Unstructured) (*v1alpha1.AccessBinding, error)); ok {
		return rf(ctx, roleName, namespace, groups, app, project)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string, *unstructured.Unstructured, *unstructured.Unstructured) *v1alpha1.AccessBinding); ok {
		r0 = rf(ctx, roleName, namespace, groups, app, project)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.AccessBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string, *unstructured.Unstructured, *unstructured.Unstructured) error); ok {
		r1 = rf(ctx, roleName, namespace, groups, app, project)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetGrantingAccessBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrantingAccessBinding'
type MockService_GetGrantingAccessBinding_Call struct {
	*mock.Call
}

// GetGrantingAccessBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - roleName string
//   - namespace string
//   - groups []string
//   - app *unstructured.Unstructured
//   - project *unstructured.Unstructured
func (_e *MockService_Expecter) GetGrantingAccessBinding(ctx interface{}, roleName interface{}, namespace interface{}, groups interface{}, app interface{}, project interface{}) *MockService_GetGrantingAccessBinding_Call {
	return &MockService_GetGrantingAccessBinding_Call{Call: _e.mock.On("GetGrantingAccessBinding", ctx, roleName, namespace, groups, app, project)}
}

func (_c *MockService_GetGrantingAccessBinding_Call) Run(run func(ctx context.Context, roleName string, namespace string, groups []string, app *unstructured.Unstructured, project *unstructured.Unstructured)) *MockService_GetGrantingAccessBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string), args[4].(*unstructured.Unstructured), args[5].(*unstructured.Unstructured))
	})
	return _c
}

func (_c *MockService_GetGrantingAccessBinding_Call) Return(_a0 *v1alpha1.AccessBinding, _a1 error) *MockService_GetGrantingAccessBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetGrantingAccessBinding_Call) RunAndReturn(run func(context.Context, string, string, []string, *unstructured.Unstructured, *unstructured.Unstructured) (*v1alpha1.AccessBinding, error)) *MockService_GetGrantingAccessBinding_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessRequests provides a mock function with given fields: ctx, key, sort
func (_m *MockService) ListAccessRequests(ctx context.Context, key *backend.AccessRequestKey, sort bool) ([]*v1alpha1.AccessRequest, error) {
	ret := _m.Called(ctx, key, sort)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessRequests")
	}

	var r0 []*v1alpha1.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, bool) ([]*v1alpha1.AccessRequest, error)); ok {
		return rf(ctx, key, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *backend.AccessRequestKey, bool) []*v1alpha1.AccessRequest); ok {
		r0 = rf(ctx, key, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.AccessRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *backend.AccessRequestKey, bool) error); ok {
		r1 = rf(ctx, key, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListAccessRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessRequests'
type MockService_ListAccessRequests_Call struct {
	*mock.Call
}

// ListAccessRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - key *backend.AccessRequestKey
//   - sort bool
func (_e *MockService_Expecter) ListAccessRequests(ctx interface{}, key interface{}, sort interface{}) *MockService_ListAccessRequests_Call {
	return &MockService_ListAccessRequests_Call{Call: _e.mock.On("ListAccessRequests", ctx, key, sort)}
}

func (_c *MockService_ListAccessRequests_Call) Run(run func(ctx context.Context, key *backend.AccessRequestKey, sort bool)) *MockService_ListAccessRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*backend.AccessRequestKey), args[2].(bool))
	})
	return _c
}

func (_c *MockService_ListAccessRequests_Call) Return(_a0 []*v1alpha1.AccessRequest, _a1 error) *MockService_ListAccessRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListAccessRequests_Call) RunAndReturn(run func(context.Context, *backend.AccessRequestKey, bool) ([]*v1alpha1.AccessRequest, error)) *MockService_ListAccessRequests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
