// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	v1alpha1 "github.com/argoproj-labs/ephemeral-access/api/ephemeral-access/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// MockPersister is an autogenerated mock type for the Persister type
type MockPersister struct {
	mock.Mock
}

type MockPersister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersister) EXPECT() *MockPersister_Expecter {
	return &MockPersister_Expecter{mock: &_m.Mock}
}

// GetAccessRequest provides a mock function with given fields: ctx, name, namespace
func (_m *MockPersister) GetAccessRequest(ctx context.Context, name string, namespace string) (*v1alpha1.AccessRequest, error) {
	ret := _m.Called(ctx, name, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessRequest")
	}

	var r0 *v1alpha1.AccessRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.AccessRequest, error)); ok {
		return rf(ctx, name, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.AccessRequest); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.AccessRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPersister_GetAccessRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessRequest'
type MockPersister_GetAccessRequest_Call struct {
	*mock.Call
}

// GetAccessRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockPersister_Expecter) GetAccessRequest(ctx interface{}, name interface{}, namespace interface{}) *MockPersister_GetAccessRequest_Call {
	return &MockPersister_GetAccessRequest_Call{Call: _e.mock.On("GetAccessRequest", ctx, name, namespace)}
}

func (_c *MockPersister_GetAccessRequest_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockPersister_GetAccessRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPersister_GetAccessRequest_Call) Return(_a0 *v1alpha1.AccessRequest, _a1 error) *MockPersister_GetAccessRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPersister_GetAccessRequest_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.AccessRequest, error)) *MockPersister_GetAccessRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPersister creates a new instance of MockPersister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersister {
	mock := &MockPersister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
