apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    {{- include "chart.labels" . | nindent 4 }}
  name: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: controller
      labels:
        app.kubernetes.io/component: controller
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: controller
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-ephemeral-access
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - args:
        - controller
        env:
        - name: EPHEMERAL_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: controller.log.level
              name: controller-cm
              optional: true
        - name: EPHEMERAL_LOG_FORMAT
          valueFrom:
            configMapKeyRef:
              key: controller.log.format
              name: controller-cm
              optional: true
        - name: EPHEMERAL_METRICS_ADDR
          valueFrom:
            configMapKeyRef:
              key: controller.metrics.address
              name: controller-cm
              optional: true
        - name: EPHEMERAL_METRICS_SECURE
          valueFrom:
            configMapKeyRef:
              key: controller.metrics.secure
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_PORT
          valueFrom:
            configMapKeyRef:
              key: controller.port
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_ENABLE_LEADER_ELECTION
          valueFrom:
            configMapKeyRef:
              key: controller.leader.election.enabled
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_HEALTH_PROBE_ADDR
          valueFrom:
            configMapKeyRef:
              key: controller.health.probe.address
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_ENABLE_HTTP2
          valueFrom:
            configMapKeyRef:
              key: controller.http2.enabled
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_REQUEUE_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: controller.requeue.interval
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_REQUEST_TIMEOUT
          valueFrom:
            configMapKeyRef:
              key: controller.request.timeout
              name: controller-cm
              optional: true
        - name: EPHEMERAL_CONTROLLER_ACCESS_REQUEST_TTL
          valueFrom:
            configMapKeyRef:
              key: controller.access.request.ttl
              name: controller-cm
              optional: true
        image: "{{ .Values.controller.image.repository }}:{{ default .Chart.AppVersion .Values.controller.image.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        name: controller
        ports:
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: controller
      terminationGracePeriodSeconds: 10
