apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
  name: backend-metrics
  namespace: system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app.kubernetes.io/component: backend
