apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
  name: backend-metrics
  namespace: system
spec:
  ports:
    # Metrics currently not implemented for server.
    # Should be served on another port to use different connection pool
    - name: metrics
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app.kubernetes.io/component: backend
