---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-role
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - application
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - appproject
    verbs:
      - get
  - apiGroups:
      - ephemeral-access.argoproj-labs.io
    resources:
      - accessrequests
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ephemeral-access.argoproj-labs.io
    resources:
      - roletemplates
    verbs:
      - get
