apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: argocd-ephemeral-access
    app.kubernetes.io/managed-by: kustomize
  name: controller-metrics
  namespace: system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app.kubernetes.io/component: controller
