name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    name: Compile
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          # see https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs
          cache-dependency-path: |
            go.sum
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go mod download
      - name: build
        run: make
      - name: test
        run: make test
